version: '3'
services:
  akaunting-mysql:
    image: mysql:5.7
    container_name: akaunting-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: akaunting_root_password
      MYSQL_DATABASE: akaunting_db
      MYSQL_USER: akaunting_admin
      MYSQL_PASSWORD: akaunting_password
  akaunting-app:
    build: .
    container_name: akaunting-app
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
    environment:
      APP_DEBUG: "true"
    links:
      - akaunting-mysql
